default:
    trainer: ppo
    batch_size: 64
    beta: 2.0e-3
    buffer_size: 512
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.945
    learning_rate: 6.0e-4
    learning_rate_schedule: linear
    max_steps: 8.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 5000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
